### ISSUE TITLE
Implement Caching on a Credentials level

### ISSUE THREAD

**Issue by bshaffer** [google/google-auth-library-php#121]
Caching could be implemented on a Credentials level instead of a Middleware/Subscriber level.

PROS:
 - Caching happens closer to the actual token fetching, which will allow more libraries to take advantage of caching hands-free (see https://github.com/googleapis/gax-php/issues/26)
 - Straightforward refactoring

CONS:
 - Breaking BC (again)

`ScopedAccessToken` subscriber/middleware has caching. We could leave the caching logic in there.

**Comment by tmatsuo** [comment]
I think I like it

**Comment by bshaffer** [comment]
implemented in #123
