### ISSUE TITLE
Upgrade guzzle version to fix HTTP_PROXY bug?

### ISSUE THREAD

**Issue by thinkerou** [google/google-auth-library-php#124]
Links: https://httpoxy.org/
guzzle have fixed now, link: https://github.com/guzzle/guzzle/commit/9d521b23146cb6cedd772770a2617fd6cbdb1596#diff-ff73e042e738204c6da009e2ed19f783L166
So, I think that we should upgrade the version of guzzle.

**Comment by bshaffer** [comment]
This library will automatically update to the fixed version of guzzle with the current requirements.
