### ISSUE TITLE
Missing grant_type after repeat calls to fetchAuthToken()

### ISSUE THREAD

**Issue by dwsupplee** [google/google-auth-library-php#130]
More information: https://github.com/googleapis/gax-php/pull/33#issuecomment-235917456

**Comment by michaelbausor** [comment]
The issue appear to be related to the call here:
https://github.com/google/google-auth-library-php/blob/master/src/OAuth2.php#L494

The $credentials object returned doesn't necessarily contain a refreshToken. In this case, the updateToken method will replace the existing refeshToken with null:
https://github.com/google/google-auth-library-php/blob/master/src/OAuth2.php#L603
