### ISSUE TITLE
Retrieving user information

### ISSUE THREAD

**Issue by mikemeier** [google/google-auth-library-php#136]
How can I retrieve for example the authenticated userId and/or email with this library?

**Comment by bshaffer** [comment]
An `id_token` will be returned with any authorization request including the `openid` scope. You can then decode the `id_token` to receive the userID and email. We use the `firebase/jwt` library to do this in the `google/apiclient` library ([code](https://github.com/google/google-api-php-client/blob/master/src/Google/AccessToken/Verify.php#L96), [example](https://github.com/GoogleCloudPlatform/getting-started-php/blob/master/4-auth/src/controllers.php#L198))

In that example we use the scope `https://www.googleapis.com/auth/userinfo.profile`, so try doing that if `openid` doesn't do the trick.
