### ISSUE TITLE
minimum-stability

### ISSUE THREAD

**Issue by LuizOliveira203** [google/google-auth-library-php#141]
Hello, I'm trying to add the Google/Auth library trhu composer using PhPStorm. The composer is working, I added googleads/googleads-php-lib to test and worked out fine, but when I try to add google/auth library I get the following error:
  Problem 1
    - The requested package google/auth No version set (parsed as 1.0.0) is satisfiable by google/auth[No version set (parsed as 1.0.0)] but these conflict with your requirements or minimum-stability.

I've downloaded the lastest google-auth-library-php release, extracted the files into my project path, updated the composer and then tried to install google/auth library, the problem is persisting no matter what.. Does anyone know wath can I do??

Thanks,

**Comment by Voziv** [comment]
The problem is that there is no version `1.0.0`. You might have mistaken `v0.10` or `v0.11.x` for that.

I have this in my `composer.json` file and it works fine. It installs
```
{
  "require": {
    "google/auth"             : "^0.11",
    "google/apiclient"        : "^2.1"
  }
}
```

and it installs just fine.

```
Updating dependencies (including require-dev)
  - Installing google/apiclient-services (v0.8)
    Downloading: 100%

  - Installing google/auth (v0.11.1)
    Downloading: 100%

  - Installing google/apiclient (v2.1.0)
    Downloading: 100%
```

**Comment by LuizOliveira203** [comment]
Funny, my composer.json was fine, with all the correct versions setted. I excluded the whole thing and installed everything again, now its working fine... But thanks for the attention!
