### ISSUE TITLE
CacheTrait.php:38 Call to a member function get() on a non-object

### ISSUE THREAD

**Issue by PaulNaylor** [google/google-auth-library-php#144]
I'm getting about 1 of these a day. 
I'm wondering, if ...
`$this->cache->getItem($key)`
...returns null, perhaps we should just return null rather that calling 
`$cacheItem->get();`
... and crashing, which is the current behaviour for getCachedValue();

**Comment by bshaffer** [comment]
The idea is `$this->cache->getItem($key)` always returns a cache item. Looking at the code, I can't find a scenario where this would happen. Are you using a custom cache type, or are you using the [MemoryCache](https://github.com/google/google-auth-library-php/blob/master/src/Cache/MemoryCacheItemPool.php) which is used by default?

**Comment by bshaffer** [comment]
@PaulNaylor Can you provide some more info here?

**Comment by JustinBeckwith** [comment]
Greetings!  We haven't heard back in a while.  If you're still having issues... please do let us know and we'll re-open the bug!
