### ISSUE TITLE
AppIdentityCredentials::onAppEngine() & getenv calls failing in appengine local development server

### ISSUE THREAD

**Issue by dwsupplee** [google/google-auth-library-php#146]
Hey guys,

Should the following calls be expected to work while executing code in the app engine local development server? The getenv calls in `CredentialsLoader` are returning false for me.

https://github.com/google/google-auth-library-php/blob/master/src/Credentials/AppIdentityCredentials.php#L77
https://github.com/google/google-auth-library-php/blob/master/src/CredentialsLoader.php#L90
https://github.com/google/google-auth-library-php/blob/master/src/CredentialsLoader.php#L65

For more information: https://github.com/GoogleCloudPlatform/google-cloud-php/issues/340#issuecomment-283860335

**Comment by bshaffer** [comment]
This seems like a pretty easy fix, we would just need to change `onAppEngine` to the following:

```php
    public static function onAppEngine()
    {
        return isset($_SERVER['SERVER_SOFTWARE']) && (
           0 === strpos($_SERVER['SERVER_SOFTWARE'], 'Google App Engine') ||
           0 === strpos($_SERVER['SERVER_SOFTWARE'], 'Development/')
        );
    }
```

Although checking for `'Development/'` does seem a little too loose of a requirement, so we could do this instead:


```php
    /**
     * Determines if this an App Engine instance, by accessing the SERVER_SOFTWARE
     * environment variable (prod) or the APPENGINE_RUNTIME environment variable (dev).
     *
     * @return true if this an App Engine Instance, false otherwise
     */
    public static function onAppEngine()
    {
        $appEngineProduction = isset($_SERVER['SERVER_SOFTWARE']) && 
            0 === strpos($_SERVER['SERVER_SOFTWARE'], 'Google App Engine');
        if ($appEngineProduction) {
            return true;
        }
        $appEngineDevAppServer = isset($_SERVER['APPENGINE_RUNTIME']) && 
           $_SERVER['APPENGINE_RUNTIME'] == 'php';
        if ($appEngineDevAppServer) {
            return true;
        }
        return false;
    }
```

**Comment by dwsupplee** [comment]
Thanks for the fix! :)
