### ISSUE TITLE
Update firebase/php-jwt dependency.

### ISSUE THREAD

**Issue by SamMousa** [google/google-auth-library-php#157]
Currently this library requires version 2, 3 or 4 of `firebase/php-jwt`.

Version 5 has been released a few days ago and as far as I can tell does not list any backwards compatibility breaks.
This should be confirmed, but if that's the case then it makes sense to also allow version 5.

https://github.com/firebase/php-jwt#500--2017-06-26

**Comment by siwinski** [comment]
`google/apiclient`'s dependency has been updated to allow `firebase/php-jwt` `~5.0` [1][2] but since it requires this package, it must be updated here as well

[1] https://github.com/google/google-api-php-client/pull/1258
[2] https://github.com/google/google-api-php-client/releases/tag/v2.2.0

**Comment by Lexinek** [comment]
Bump, it would be useful for us as we have `"firebase/php-jwt": "^5.0"` composer dependency in our project, we have to alias it to 4.0 to be able to have `google/apiclient` dependency

**Comment by bshaffer** [comment]
added in [`v1.0.1`](https://github.com/google/google-auth-library-php/releases/tag/v1.0.1)
