### ISSUE TITLE
Update guzzlehttp/psr7 to 1.4

### ISSUE THREAD

**Issue by shadoWalker89** [google/google-auth-library-php#169]
Hi,

Is it possible to update the dependency of "guzzlehttp/psr7" to support version 1.4
because using 

"guzzlehttp/guzzle": "~6.0"

requires 

"guzzlehttp/psr7": "^1.4"

**Comment by bshaffer** [comment]
@shadoWalker89 our composer requirements are set to `guzzlehttp/psr7:~1.2`, which includes `guzzlehttp/psr7:^1.4`. So whatever composer requirements error you are receiving, it isn't a result of this library.

Try running `composer update` to fix the problem.
