### ISSUE TITLE
Headers being overwritten and not merged

### ISSUE THREAD

**Issue by erictinocopro** [google/google-auth-library-php#180]
While working with GCS PHP library, I've found a bug on auth library.
Using encrypting options makes the upload fail cause headers are not correct.
After digging that for a while, it turns out that root cause is on file **src/HttpHandler/Guzzle5HttpHandler.php** row 112.

<pre><code class="php">
    private function createGuzzle5Request(RequestInterface $request, array $options)
    {

        return $this->client->createRequest(
            $request->getMethod(),
            $request->getUri(),
            array_merge([
                'headers' => $request->getHeaders(),
                'body' => $request->getBody(),
            ], $options)
        );
    }
</code></pre>

should be 

<pre><code class="php">
    private function createGuzzle5Request(RequestInterface $request, array $options)
    {

        return $this->client->createRequest(
            $request->getMethod(),
            $request->getUri(),
            array_merge_recursive([
                'headers' => $request->getHeaders(),
                'body' => $request->getBody(),
            ], $options)
        );
    }
</code></pre>

using **array_merge_recursive** ensure we merge headers properly.

I was keen on doing a PR for you but I can't ... :/ 
Thanks for your help 

E.

**Comment by bshaffer** [comment]
fixed in #186 

Thank you for finding this!
