### ISSUE TITLE
Please provide a way to disable the warning for 3 legged OAuth credentials

### ISSUE THREAD

**Issue by steffenweber** [google/google-auth-library-php#201]
Commit https://github.com/google/google-auth-library-php/commit/8057ceda3e324304a6443b82f1a56f52cd9e600d introduced a "warning for 3 legged OAuth credentials".

I'm using the YouTube Data API to manage a single YouTube channel. The YouTube Data API doesn't support service accounts. Therefore, I'm using "Offline/long-lived access to the YouTube API" as recommended by the documentation: https://developers.google.com/youtube/v3/guides/moving_to_oauth#offlinelong-lived-access-to-the-youtube-api

It therefore seems like my use-case is legitimate and that I should silence this warning. Right?

What is the recommended way to silence this warning? Should I call `error_reporting(E_ALL & ~E_USER_WARNING)`?

The problem with this approach is that the warning is not generated during the initialization of the `Google_Client` object. Instead, the warning is emitted indirectly later on, for example when some call in `Google_Service_YouTube` happens. I'd therefore have to disable the E_USER_WARNING in lots of places (which feels wrong) or globally (and therefore unintentionally suppress more warnings than I'd like to).

What do you think about providing a way to programmatically disable the "warning for 3 legged OAuth credentials" during construction of the `Google_Client` object?

**Comment by dwsupplee** [comment]
@steffenweber we feel your pain here, sorry for the trouble. A programmatic solution to disable the warning is definitely on the table. In the meantime, the best suggestion I have would be to avoid the warning by pinning to a release of the library prior to 1.3.1. - `"google/auth": "1.0.0 - 1.3.0"`

**Comment by tmatsuo** [comment]
@steffenweber 

The fix has landed with the newly tagged v1.3.2. If you still see the warning and want to suppress it, you can set `SUPPRESS_GCLOUD_CREDS_WARNING` envvar to `true`.

Sorry about the trouble.

**Comment by steffenweber** [comment]
Thank you!
