### ISSUE TITLE
PHP Default Credentials check for and user GAE App Identity Credentials

### ISSUE THREAD

**Issue by anthmgoogle** [google/google-auth-library-php#46]
The current implementation of ApplicationDefaultCredentials in PHP does not yet support the GAE App Identty. The first class GAE lanauges should check for this environment and use this identity after checking for the environment variable and well-known-file, but before checking for GCE.

**Comment by tbetbetbe** [comment]
The AppIdentity logic seems fairly straightforward, cf [AppIdentity.php](https://github.com/google/google-auth-library-php/blob/ae88d7ae96f96c6012bbf77a5bb0a8acbe790a32/src/Google/Auth/AppIdentity.php).  It was an omission on my part to remove that file before porting the logic to the new Guzzle-aware interfaces

To resolve this issue, it should be sufficient to
- [ ] restore a version of AppIdentify.php that implements FetchAuthTokenInterface
- [ ] update ApplicationDefaultCredentials.php to use it

**Comment by tbetbetbe** [comment]
@bshaffer PTAL
