### ISSUE TITLE
Apache2 / php on a Mac  -- Documentation suggestions...

### ISSUE THREAD

**Issue by lesv** [google/google-auth-library-php#50]
For a Mac, you can enable Apache2 using [these instructions](http://coolestguidesontheplanet.com/get-apache-mysql-php-phpmyadmin-working-osx-10-10-yosemite/).

Once that is done, you should can set either the `HOME` or the `GOOGLE_APPLICATION_CREDENTIALS` in either .htaccess or /etc/apache2/users/userName.conf
```
SetEnv GOOGLE_APPLICATION_CREDENTIALS /Users/lesv/Downloads/Abelana-5ca655910529.json
# SetEnv HOME /Users/lesv/
```

**Comment by tbetbetbe** [comment]
Thanks, we should add this to the README.md

**Comment by bshaffer** [comment]
I've added `putenv` [to the README](https://github.com/google/google-auth-library-php/blob/master/README.md#download-your-service-account-credentials-json-file), and mentioned there are other ways to set environment variables (such as `.htaccess` and `apache configs`). I believe this will be sufficient.
