### ISSUE TITLE
JwtAccess Credentials Feature

### ISSUE THREAD

**Issue by anthmgoogle** [google/google-auth-library-php#51]
Tracking completion of implementation of JwtAccess Credentials for service accounts for PHP. This is a service account that passes a JWT directly as an a bearer token instead of exchanging for an access token.

For reference, the Java implementation:
https://github.com/google/google-auth-library-java/blob/master/oauth2_http/java/com/google/auth/oauth2/ServiceAccountJwtAccessCredentials.java

**Comment by stanley-cheung** [comment]
Already fixed by #44 ?

**Comment by tbetbetbe** [comment]
That's correct,  #44 add this.
I will close this bug, but please re-open with more detail if you're referring to something else
