### ISSUE TITLE
Promote OAuth2 service account to Jwt Access credentials

### ISSUE THREAD

**Issue by anthmgoogle** [google/google-auth-library-php#52]
Application Default Credentials can return Oauth2 service account credentials. gRPC can use more efficient JwtAccess credentials in place of this if no scopes have been specified. This tracks logic to detect this case and "promote" the credentials to JwtAccess form with the same identity properties if the OAuth2 form is passed in for use by gRPC.

Logic should be similar to this (in Java):

if (credentials instanceof ServiceAccountOAuth2Credentials) {
ServiceAccountOAuth2Credentials serviceAccount = 
(ServiceAccountOAuth2Credentials)credentials;
if (serviceAccount.getScopes().length() == 0) {
credentials = new ServiceAccountJwtAccessCredentials(
serviceAccount.getAccountEmail(),
serviceAccount.getPrivateKey(),
serviceAccount.getPrivateKeyId());
}
}

**Comment by tbetbetbe** [comment]
This is already implemented, it was added in #44.

Please see https://github.com/google/google-auth-library-php/blob/master/src/ServiceAccountCredentials.php#L132

Will close this, please feel free to re-open if there is some confusion about the requiremen
