### ISSUE TITLE
No sample code provided

### ISSUE THREAD

**Issue by erickoledadevrel** [google/google-auth-library-php#60]
As far as I can tell, this library doesn't provide any sample code showing how to use it. I would expect to see a brief overview in the README, with a complete working sample application that uses it.

**Comment by bshaffer** [comment]
Agreed. We will definitely fix this by adding the sample code found [here](https://github.com/google/google-auth-library-php/blob/master/src/ApplicationDefaultCredentials.php#L76) to the README, along with additional info on how to set up your Service Account Credentials and set the `GOOGLE_APPLICATION_CREDENTIALS` environment variable.

**Comment by bshaffer** [comment]
addressed in #63
