### ISSUE TITLE
Add getter on subscribers for auth identifiers

### ISSUE THREAD

**Issue by bshaffer** [google/google-auth-library-php#73]
- `AuthTokenFetcher` requires `['auth' => 'google_auth']`
 - `ScopedAccessToken` requires `['auth' => 'scoped']`
 - `Simple` requires `['auth' => 'simple']`

It would be helpful to have a `getAuthIdentifier` method on these classes so we can obtain the values they expect programmatically.

Although, I am not sure why these are required in the first place, so maybe I'm missing something. I assume the reasoning for requiring the `auth` property to be set in `Guzzle` is best practices, and so it's ok to programmatically apply it.

**Comment by dwsupplee** [comment]
As far as I can tell these values are only used here,

https://github.com/google/google-auth-library-php/blob/213ca8725ec3e3c5f5ee6560fa9f277b1cde0994/src/AuthTokenFetcher.php#L106-L108

I can see a case where you may want to handle different auth types, but that doesn't seem to be the case here - we just prevent the request from working if the configuration isn't provided.

I don't believe it's a best practice to include this and would be in favor of removing the identifiers altogether. There isn't really a case you *don't* want to authenticate the request, so why require additional configuration?

**Comment by bshaffer** [comment]
I agree with @dwsupplee, I'm not sure why this design decision was made. Maybe @tbetbetbe can provide some insight?

**Comment by bshaffer** [comment]
It allows the user to set up their HTTP client with multiple auth classes (say in a container) and then choose at runtime which to use. In general, it also makes the authentication more explicit.

**Comment by bshaffer** [comment]
closing - this is not a real issue, just an inconvenience.
