### ISSUE TITLE
Pass Expire on Set instead of Get in CacheInterface

### ISSUE THREAD

**Issue by caleblloyd** [google/google-auth-library-php#76]
Modern Key-Value stores such as Redis and Memcached set the expire-time of a key during the Set operation by setting a TTL for a key.

The CacheInterface instead passes the expire option in the Get function, which makes things difficult because now we have to store a timestamp during Set function and check it in the Get function.  Additionally, the key can no longer be automatically garbage collected by the Key-Value store..

Expire param should be switched to the Set operation.

**Comment by bshaffer** [comment]
This seems obvious to me as well. Perhaps @tbetbetbe could shed some light on why this is not the case?

Unfortunately [PSR-6](https://github.com/php-fig/fig-standards/blob/master/proposed/cache.md) seems to have a ways to go, so I don't think it's worth implementing at this time.

**Comment by tbetbetbe** [comment]
This is a reasonable change to make.

When I defined CacheInterface, the goal was to make it easy to adapt the
existing Cache implementations in google api client library.  I'm open to
changing this now that api client library actually does depend on the auth
library.

On 17 October 2015 at 04:06, Brent Shaffer <notifications@github.com> wrote:

> This seems obvious to me as well. Perhaps @tbetbetbe
> <https://github.com/tbetbetbe> could shed some light on why this is not
> the case?
>
> Unfortunately PSR-6
> <https://github.com/php-fig/fig-standards/blob/master/proposed/cache.md>
> seems to have a ways to go, so I don't think it's worth implementing at
> this time.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/google-auth-library-php/issues/76#issuecomment-148808415>
> .
>



-- 
This email may be confidential or privileged.  If you received this
communication by mistake, please don't forward it to anyone else (it may
contain confidential or privileged information), please erase all copies of
it, including all attachments, and please let the sender know it went to
the wrong person. Thanks.

**Comment by bshaffer** [comment]
we've now implemented PSR-6 support, so this is no longer valid.
