### ISSUE TITLE
Help: How to call my own API hosted on https://xxx.appspot.com/myapp

### ISSUE THREAD

**Issue by jonnyijapan** [google/google-auth-library-php#90]
I need to post some data that is generated periodically to my GAE app using a PHP script. I don't really understand how to make this library work for that. I generated a service key which my script points to like this putenv('GOOGLE_APPLICATION_CREDENTIALS=/Users/me/myfile.json');
However the docs at https://github.com/google/google-auth-library-php talks about scopes like Drive etc, and I am not using Drive, just my own API at that URL.
I used to have this script automatically uploading data last year until that way of authenticating was deprecated.
What is the "scope" of a GAE app? How would the sample code below "Call the APIs" be changed to allow POSTs to an GAE app?

**Comment by bshaffer** [comment]
Hmm, are you using GAE's [admin authentication](https://cloud.google.com/appengine/docs/python/config/appconfig?hl=en#Python_app_yaml_Requiring_login_or_administrator_status) in `app.yaml`? If not, how is your authentication defined? You could try something like this:

```php
$client = new Google_Client();
$client->setAuthConfig('/Users/me/myfile.json');
$http = $client->authorize();

$request = new GuzzleHttp\Psr7\Request('POST', 'http://myapp.appspot.com/my-api', [], $postData);
$response = $http->send($request);
```

Please let me know if this is helpful.

**Comment by jonnyijapan** [comment]
I do use GAE's admin authentication. However I get Class 'Google_Client' not found. Do I need another library than google-auth-library-php for that?

**Comment by jonnyijapan** [comment]
I changed to 1.0...

```
{
    "require": {
		"google/apiclient": "1.0.*@beta",
		"google/auth": "^0.5.0"
    }
}
```

and now get error on the Google_Client->setAuthConfig('....path.json') line:

```
PHP Fatal error:  Uncaught exception 'Google_Exception' with message 'Invalid client secret JSON file.' in /Users/somepath.json
```

I do use "Service account" as per the documentation here https://github.com/google/google-auth-library-php - do I need another json key file?

**Comment by bshaffer** [comment]
Try upgrading to "google/apiclient": "~2.0@RC"

**Comment by jonnyijapan** [comment]
Ok now I get
```
PHP Fatal error:  Uncaught exception 'GuzzleHttp\Exception\ClientException' with message 'Client error: `POST https://www.googleapis.com/oauth2/v3/token` resulted in a `400 Bad Request` response:
{
 "error": "invalid_scope",
 "error_description": "Empty or missing scope not allowed."
}
```

Just to be clear, I am not calling any Google API, just my own API that I created at xxx.appspot.com/someapi.

**Comment by bshaffer** [comment]
This library is meant for calling Google APIs. If you're exposing your own API, then you will be implementing the authentication.

**Comment by jonnyijapan** [comment]
The API is mine of course but the authentication is Google's. I haven't had time to look into this.

**Comment by bshaffer** [comment]
Then you should try following the instructions in the readme to attach the
appropriate middleware to your guzzle http client, and then just make the
request to your own api endpoint. This will send the request with an access
token in the header. You could also send in the Id token and verify on the
server side that it's indeed from Google.
